services:
#  mongodb:
#    image: 'mongo:latest'
#    environment:
#      - 'MONGO_INITDB_DATABASE=mydatabase'
#      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
#      - 'MONGO_INITDB_ROOT_USERNAME=root'
#    ports:
#      - '27017'
#  mysql:
#    image: mysql
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: example_password
#      MYSQL_DATABASE: example_database
#    ports:
#      - "3306:3306"
#    volumes:
#      -./data:/var/lib/mysql
  postgres:
    image: postgres:alpine3.18
    restart: always
    environment:
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example_password
      POSTGRES_DB: example_database
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
